Delete "$INSTDIR\*.pyd"
Delete "$INSTDIR\*.dll"
Delete "$INSTDIR\*.zip"
Delete "$INSTDIR\*.ini"
Delete "$INSTDIR\*.txt"
Delete "$INSTDIR\CHANGELOG"
Delete "$INSTDIR\LICENSE"
Delete "$INSTDIR\README.md"
Delete "$INSTDIR\cards_server.exe"
Delete "$INSTDIR\cards_client.exe"
RMDir /r "$INSTDIR\img"
RMDir "$INSTDIR"
